# Generated by Django 4.0.2 on 2022-03-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_source_remove_food_source_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
